#> minecraft_but.core:modifiers/random_structures/place_structure
#Function automatically generated by NodeJS script (src/index.js) to place a random structure
# 31 total structures 
# @within minecraft_but.core:modifiers/random_structures/**
# @context marker

#> Get random number
scoreboard players set $min random 1
scoreboard players set $max random 31
function minecraft_but.core:aps/rng/range

#> Place random structure
execute if score $out random matches 0 run place structure minecraft:ancient_city ~ ~ ~
execute if score $out random matches 1 run place structure minecraft:buried_treasure ~ ~ ~
execute if score $out random matches 2 run place structure minecraft:desert_pyramid ~ ~ ~
execute if score $out random matches 3 run place structure minecraft:end_city ~ ~ ~
execute if score $out random matches 4 run place structure minecraft:igloo ~ ~ ~
execute if score $out random matches 5 run place structure minecraft:jungle_pyramid ~ ~ ~
execute if score $out random matches 6 run place structure minecraft:mineshaft ~ ~ ~
execute if score $out random matches 7 run place structure minecraft:mineshaft_mesa ~ ~ ~
execute if score $out random matches 8 run place structure minecraft:fortress ~ ~ ~
execute if score $out random matches 9 run place structure minecraft:bastion_remnant ~ ~ ~
execute if score $out random matches 10 run place structure minecraft:nether_fossil ~ ~ ~
execute if score $out random matches 11 run place structure minecraft:monument ~ ~ ~
execute if score $out random matches 12 run place structure minecraft:ocean_ruin_cold ~ ~ ~
execute if score $out random matches 13 run place structure minecraft:ocean_ruin_warm ~ ~ ~
execute if score $out random matches 14 run place structure minecraft:pillager_outpost ~ ~ ~
execute if score $out random matches 15 run place structure minecraft:ruined_portal ~ ~ ~
execute if score $out random matches 16 run place structure minecraft:ruined_portal_desert ~ ~ ~
execute if score $out random matches 17 run place structure minecraft:ruined_portal_jungle ~ ~ ~
execute if score $out random matches 18 run place structure minecraft:ruined_portal_swamp ~ ~ ~
execute if score $out random matches 19 run place structure minecraft:ruined_portal_mountain ~ ~ ~
execute if score $out random matches 20 run place structure minecraft:ruined_portal_ocean ~ ~ ~
execute if score $out random matches 21 run place structure minecraft:ruined_portal_nether ~ ~ ~
execute if score $out random matches 22 run place structure minecraft:shipwreck ~ ~ ~
execute if score $out random matches 23 run place structure minecraft:shipwreck_beached ~ ~ ~
execute if score $out random matches 24 run place structure minecraft:stronghold ~ ~ ~
execute if score $out random matches 25 run place structure minecraft:swamp_hut ~ ~ ~
execute if score $out random matches 26 run place structure minecraft:village_plains ~ ~ ~
execute if score $out random matches 27 run place structure minecraft:village_desert ~ ~ ~
execute if score $out random matches 28 run place structure minecraft:village_savanna ~ ~ ~
execute if score $out random matches 29 run place structure minecraft:village_snowy ~ ~ ~
execute if score $out random matches 30 run place structure minecraft:village_taiga ~ ~ ~
execute if score $out random matches 31 run place structure minecraft:mansion ~ ~ ~

#> Visuals
function minecraft_but.core:modifiers/random_structures/visuals

#> Kill marker
kill @s