#> abchc:menu/modifiers/core/chaos
# List of Chaos (chaos) modifiers. This file is automatically generated.
# @within abchc:menu/**
# @context menu player

#> Click sound
function abchc:menu/actions/click

#> Update page score
scoreboard players set @s abch.menu.page 12

#> Disable sendCommandFeedback
gamerule sendCommandFeedback false

#> Set sendCommandFeedback back next tick
schedule function abchc:menu/actions/enable_feedback 1t append

#> Header

# If there are no expansion loaded, clicking top bar sends player back to main menu.
# Doing this gets rid of that unnecessary step between directory and page 1 here.
execute unless score $total abch.expansion matches 1.. run tellraw @s ["\n\n\n\n\n\n\n\n\n\n\n\n",{"text":"---------------------------------------------","color":"#0F21C6"},"\n",{"text":"←|","color":"#ECEFF5","clickEvent":{"action":"run_command","value":"/function abchc:menu/actions/back_to_main"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click here to go back to the main menu.","color":"#ECEFF5"}]}},{"text":" Chaos","color":"#FF0000","clickEvent":{"action":"run_command","value":"/function abchc:menu/actions/back_to_main"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click here to go back to the main menu.","color":"#ECEFF5"}]}},"\n",{"text":"---------------------------------------------","color":"#0F21C6"}]

# If there is an expansion loaded, clicking top bar sends the player to the modifiers directory
# which has links to the different expansion packs' modifiers pages.
execute if score $total abch.expansion matches 1.. run execute unless score $total abch.expansion matches 1.. run tellraw @s ["\n\n\n\n\n\n\n\n\n\n\n\n",{"text":"---------------------------------------------","color":"#0F21C6"},"\n",{"text":"←|","color":"#ECEFF5","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/directory"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click here to go back to the modifiers category page.","color":"#ECEFF5"}]}},{"text":" Modifier Categories","color":"#E4EB18","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/directory"},"hoverEvent":{"action":"show_text","contents":[{"text":"Click here to go back to the modifiers category page.","color":"#ECEFF5"}]}},"\n",{"text":"---------------------------------------------","color":"#0F21C6"}]

#> Modifiers
## Anvils rain from the sky (anvil_rain)
# Anvils rain from the sky threatening to crush your dreams.\n\nThe Aerial Anvil Attack Force commented on why they do it. 'We just follow gravity,' General Iron Krush said. 'Who are we to deny what the universe demands of us? We fall and we crush things. That is our purpose.'
execute unless score anvil_rain abch.toggle matches 1 run tellraw @s [{"text":" [✖] ","bold":false,"color":"#FF0000","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/on"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/config"}},{"text":"Anvils rain from the sky","bold":false,"color":"#ff0000","hoverEvent": {"action":"show_text","contents":[{"text":"Anvils rain from the sky threatening to crush your dreams.\n\nThe Aerial Anvil Attack Force commented on why they do it. 'We just follow gravity,' General Iron Krush said. 'Who are we to deny what the universe demands of us? We fall and we crush things. That is our purpose.'","color":"#ECEFF5"}]}}]



execute if score anvil_rain abch.toggle matches 1 run tellraw @s [{"text":" [✔] ","bold":false,"color":"#3ED011","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/off"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/anvil_rain/config"}},{"text":"Anvils rain from the sky","bold":false,"color":"#ff0000","hoverEvent": {"action":"show_text","contents":[{"text":"Anvils rain from the sky threatening to crush your dreams.\n\nThe Aerial Anvil Attack Force commented on why they do it. 'We just follow gravity,' General Iron Krush said. 'Who are we to deny what the universe demands of us? We fall and we crush things. That is our purpose.'","color":"#ECEFF5"}]}}]

## The world disintegrates (degradation)
# Blocks around you randomly disappear. The world gradually degradates, desintegrates. The world will not last long.
execute unless score degradation abch.toggle matches 1 run tellraw @s [{"text":" [✖] ","bold":false,"color":"#FF0000","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/on"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/config"}},{"text":"The world disintegrates","bold":false,"color":"#bf117e","hoverEvent": {"action":"show_text","contents":[{"text":"Blocks around you randomly disappear. The world gradually degradates, desintegrates. The world will not last long.","color":"#ECEFF5"}]}}]



execute if score degradation abch.toggle matches 1 run tellraw @s [{"text":" [✔] ","bold":false,"color":"#3ED011","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/off"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/degradation/config"}},{"text":"The world disintegrates","bold":false,"color":"#bf117e","hoverEvent": {"action":"show_text","contents":[{"text":"Blocks around you randomly disappear. The world gradually degradates, desintegrates. The world will not last long.","color":"#ECEFF5"}]}}]

## Everything around you turns to fire (fire_walker)
# Your journey blazes behind it a path of ashen sorrow and furious cinders.
execute unless score fire_walker abch.toggle matches 1 run tellraw @s [{"text":" [✖] ","bold":false,"color":"#FF0000","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/on"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/config"}},{"text":"Everything around you turns to fire","bold":false,"color":"#7f22fb","hoverEvent": {"action":"show_text","contents":[{"text":"Your journey blazes behind it a path of ashen sorrow and furious cinders.","color":"#ECEFF5"}]}}]



execute if score fire_walker abch.toggle matches 1 run tellraw @s [{"text":" [✔] ","bold":false,"color":"#3ED011","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/off"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/fire_walker/config"}},{"text":"Everything around you turns to fire","bold":false,"color":"#7f22fb","hoverEvent": {"action":"show_text","contents":[{"text":"Your journey blazes behind it a path of ashen sorrow and furious cinders.","color":"#ECEFF5"}]}}]

## Structures randomly spawn (random_structures)
# Structures and world generation features randomly spawn around you, making the terrain absolutely chaotic!
execute unless score random_structures abch.toggle matches 1 run tellraw @s [{"text":" [✖] ","bold":false,"color":"#FF0000","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/on"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/config"}},{"text":"Structures randomly spawn","bold":false,"color":"#7f22fb","hoverEvent": {"action":"show_text","contents":[{"text":"Structures and world generation features randomly spawn around you, making the terrain absolutely chaotic!","color":"#ECEFF5"}]}}]



execute if score random_structures abch.toggle matches 1 run tellraw @s [{"text":" [✔] ","bold":false,"color":"#3ED011","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/off"}},{"text":"[","color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/config"}},{"text":"⚙","bold":true,"color":"#CACACA","clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/config"}},{"text":"] ","color":"#CACACA","bold":false,"clickEvent":{"action":"run_command","value":"/function abchc:menu/modifiers/core/random_structures/config"}},{"text":"Structures randomly spawn","bold":false,"color":"#7f22fb","hoverEvent": {"action":"show_text","contents":[{"text":"Structures and world generation features randomly spawn around you, making the terrain absolutely chaotic!","color":"#ECEFF5"}]}}]

