# Uninstall function generated by mcf-uninstall script
# https://github.com/americanbagel/mcf-uninstall

#> Scoreboards
scoreboard objectives remove temp
scoreboard objectives remove minecraft_but.menu.page
scoreboard objectives remove minecraft_but.give_menu
scoreboard objectives remove minecraft_but.toggle
scoreboard objectives remove minecraft_but.config
scoreboard objectives remove minecraft_but.custom
scoreboard objectives remove minecraft_but.default
scoreboard objectives remove minecraft_but.random
scoreboard objectives remove minecraft_but.random.toggle
scoreboard objectives remove minecraft_but.isSpawned
scoreboard objectives remove minecraft_but.debug
scoreboard objectives remove minecraft_but.modifier
scoreboard objectives remove minecraft_but.timer
scoreboard objectives remove minecraft_but.default
scoreboard objectives remove minecraft_but.minute
scoreboard objectives remove minecraft_but.deaths
scoreboard objectives remove minecraft_but.math
scoreboard objectives remove minecraft_but.menu.sid
scoreboard objectives remove minecraft_but.menu.right_click
scoreboard objectives remove minecraft_but.menu.item
scoreboard objectives remove minecraft_but.menu.bool
scoreboard objectives remove minecraft_but.menu.page
scoreboard objectives remove minecraft_but.menu.selection
scoreboard objectives remove minecraft_but.no_walk
scoreboard objectives remove minecraft_but.sneak
scoreboard objectives remove minecraft_but.jump
scoreboard objectives remove minecraft_but.mobkill
scoreboard objectives remove minecraft_but.pacifist.kill
scoreboard objectives remove minecraft_but.blinding_damage
scoreboard objectives remove minecraft_but.damage_nausea
scoreboard objectives remove minecraft_but.death
scoreboard objectives remove minecraft_but.deadly_falls
scoreboard objectives remove minecraft_but.realistic_spiders.kill_web
scoreboard objectives remove minecraft_but.yeet
scoreboard objectives remove minecraft_but.webCdwn
scoreboard objectives remove minecraft_but.tntRand
scoreboard objectives remove minecraft_but.lightning
scoreboard objectives remove minecraft_but.anvil_rain.random
scoreboard objectives remove minecraft_but.anvil_rain.Y
scoreboard objectives remove minecraft_but.anvil_rain.Yoffset
scoreboard objectives remove minecraft_but.random_effect.effect
scoreboard objectives remove minecraft_but.random_effect.lvl
scoreboard objectives remove minecraft_but.chunk_error
scoreboard objectives remove minecraft_but.chunk_error.x
scoreboard objectives remove minecraft_but.chunk_error.z
scoreboard objectives remove minecraft_but.chunk_error.total
scoreboard objectives remove minecraft_but.vsMath
scoreboard objectives remove minecraft_but.vsConst
scoreboard objectives remove minecraft_but.vsID
scoreboard objectives remove minecraft_but.tp_arrows.UUID1
scoreboard objectives remove minecraft_but.tp_arrows.UUID2
scoreboard objectives remove minecraft_but.tp_arrows.UUID3
scoreboard objectives remove minecraft_but.tp_arrows.UUID4
scoreboard objectives remove minecraft_but.explosive_snowballs.UUID1
scoreboard objectives remove minecraft_but.explosive_snowballs.UUID2
scoreboard objectives remove minecraft_but.explosive_snowballs.UUID3
scoreboard objectives remove minecraft_but.explosive_snowballs.UUID4
scoreboard objectives remove minecraft_but.explosive_eggs.UUID1
scoreboard objectives remove minecraft_but.explosive_eggs.UUID2
scoreboard objectives remove minecraft_but.explosive_eggs.UUID3
scoreboard objectives remove minecraft_but.explosive_eggs.UUID4
scoreboard objectives remove minecraft_but.esSneak
scoreboard objectives remove minecraft_but.vsSize
scoreboard objectives remove minecraft_but.fire_rain.timer
scoreboard objectives remove minecraft_but.ender_blood.damage
scoreboard objectives remove minecraft_but.potion_food.lvl
scoreboard objectives remove minecraft_but.potion_food.effect
scoreboard objectives remove minecraft_but.suspicious_injury.damage
scoreboard objectives remove minecraft_but.suspicious_injury.effect
scoreboard objectives remove minecraft_but.ytpwyl.limit
scoreboard objectives remove minecraft_but.ytpwyl.timer
scoreboard objectives remove minecraft_but.walk_leveling.lvl
scoreboard objectives remove minecraft_but.walk_leveling.lvl2
scoreboard objectives remove minecraft_but.walk_leveling.xp
scoreboard objectives remove minecraft_but.tp_sneak.sneak
scoreboard objectives remove minecraft_but.tp_sneak.raycast
scoreboard objectives remove minecraft_but.tp_sneak.timer
scoreboard objectives remove minecraft_but.modifier.temp
scoreboard objectives remove minecraft_but.expansion
scoreboard objectives remove minecraft_but.2020_mode.x
scoreboard objectives remove minecraft_but.2020_mode.y
scoreboard objectives remove minecraft_but.2020_mode.z
scoreboard objectives remove minecraft_but.anvil_rain
scoreboard objectives remove minecraft_but.bedrock_touch.timer
scoreboard objectives remove minecraft_but.bedrock_touch.sid
scoreboard objectives remove minecraft_but.bedrock_touch.raycast
scoreboard objectives remove minecraft_but.botanophobia.deaths
scoreboard objectives remove minecraft_but.chunk_error
scoreboard objectives remove minecraft_but.chunk_error.x
scoreboard objectives remove minecraft_but.chunk_error.y
scoreboard objectives remove minecraft_but.chunk_error.z
scoreboard objectives remove minecraft_but.creeper_mobs.fuse
scoreboard objectives remove minecraft_but.deadly_colors.color
scoreboard objectives remove minecraft_but.deadly_colors.color
scoreboard objectives remove minecraft_but.deadly_colors
scoreboard objectives remove minecraft_but.death_orb.sid
scoreboard objectives remove minecraft_but.death_orb.distance
scoreboard objectives remove minecraft_but.death_orb.factor
scoreboard objectives remove minecraft_but.death_orb
scoreboard objectives remove minecraft_but.death_swap
scoreboard objectives remove minecraft_but.degradation
scoreboard objectives remove minecraft_but.ender_blood
scoreboard objectives remove minecraft_but.explosive_eggs.UUID1
scoreboard objectives remove minecraft_but.explosive_eggs.UUID2
scoreboard objectives remove minecraft_but.explosive_eggs.UUID3
scoreboard objectives remove minecraft_but.explosive_eggs.UUID4
scoreboard objectives remove minecraft_but.explosive_sight.raycast
scoreboard objectives remove minecraft_but.fast_arrows
scoreboard objectives remove minecraft_but.fire_walker.total
scoreboard objectives remove minecraft_but.fire_walker.walk
scoreboard objectives remove minecraft_but.fire_walker.crouch
scoreboard objectives remove minecraft_but.fire_walker.sprint
scoreboard objectives remove minecraft_but.fire_walker
scoreboard objectives remove minecraft_but.keep_moving.x
scoreboard objectives remove minecraft_but.keep_moving.y
scoreboard objectives remove minecraft_but.keep_moving.z
scoreboard objectives remove minecraft_but.keep_moving.still_time
scoreboard objectives remove minecraft_but.lazy_inventory.rng.math
scoreboard objectives remove minecraft_but.lazy_inventory.rng.constant
scoreboard objectives remove minecraft_but.lazy_inventory
scoreboard objectives remove minecraft_but.lazy_inventory.x
scoreboard objectives remove minecraft_but.lazy_inventory.y
scoreboard objectives remove minecraft_but.lazy_inventory.z
scoreboard objectives remove minecraft_but.limited_inventory
scoreboard objectives remove minecraft_but.limited_inventory.slots
scoreboard objectives remove minecraft_but.look_straight.x
scoreboard objectives remove minecraft_but.look_straight.y
scoreboard objectives remove minecraft_but.mermaid.timer
scoreboard objectives remove minecraft_but.mermaid.deaths
scoreboard objectives remove minecraft_but.mermaid
scoreboard objectives remove minecraft_but.no_gravity.sneak
scoreboard objectives remove minecraft_but.random_teleport
scoreboard objectives remove minecraft_but.superhot.x
scoreboard objectives remove minecraft_but.superhot.y
scoreboard objectives remove minecraft_but.superhot.z
scoreboard objectives remove minecraft_but.superhot.nx
scoreboard objectives remove minecraft_but.superhot.ny
scoreboard objectives remove minecraft_but.superhot.nz
scoreboard objectives remove minecraft_but.teleport_chorus
scoreboard objectives remove minecraft_but.teleport_chorus.eat
scoreboard objectives remove minecraft_but.tnt_rain
scoreboard objectives remove minecraft_but.toxic_water.timer
scoreboard objectives remove minecraft_but.toxic_water.deaths
scoreboard objectives remove minecraft_but.toxic_water
scoreboard objectives remove minecraft_but.troglodyte.deaths
scoreboard objectives remove minecraft_but.troglodyte.played
scoreboard objectives remove minecraft_but.troglodyte
scoreboard objectives remove minecraft_but.troglodyte.timer
scoreboard objectives remove minecraft_but.troglodyte.mercy_timer
scoreboard objectives remove minecraft_but.unstable_inv.rng.math
scoreboard objectives remove minecraft_but.unstable_inv.rng.constant
scoreboard objectives remove minecraft_but.unstable_inv.damage
scoreboard objectives remove minecraft_but.unstable_inv
scoreboard objectives remove minecraft_but.waning_wellness.death_time
scoreboard objectives remove minecraft_but.waning_wellness.max_health
scoreboard objectives remove bobscore
scoreboard objectives remove bobscore


#> Teams
team remove minecraft_but.core.color.dark_red
team remove minecraft_but.core.color.gold
team remove minecraft_but.core.color.yellow
team remove minecraft_but.core.color.green
team remove minecraft_but.core.color.blue
team remove minecraft_but.core.color.dark_purple
team remove minecraft_but.core.color.white
team remove minecraft_but.core.color.black
team remove minecraft_but.core.no_collision


#> Storage
data remove storage temp: dist.vector
data remove storage temp: dist.start
data remove storage minecraft_but.core:effect_arrows CustomPotionEffects
data remove storage minecraft_but.core:effect_arrows CustomPotionEffects
data remove storage minecraft_but.core:effect_arrows CustomPotionEffects
data remove storage minecraft_but.core:effect_arrows CustomPotionEffects
data remove storage minecraft_but.__temp__:lazy_inventory Inventory
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:limited_inventory Item
data remove storage minecraft_but.__temp__:unstable_inv Inventory
data remove storage selector path
data remove storage selector1 path2


#> Tags
tag @e remove minecraft_but.menu.init
tag @e remove minecraft_but.2020_mode.self
tag @e remove minecraft_but.anvil_rain.destroy
tag @e remove minecraft_but.tp_sneak.ray
tag @e remove minecraft_but.botanophobia.spawned
tag @e remove minecraft_but.carnivore.death_message
tag @e remove minecraft_but.chunk_error.recurse
tag @e remove minecraft_but.chunk_error.recurse
tag @e remove minecraft_but.deadly_colors.red.kill
tag @e remove minecraft_but.deadly_colors.orange.kill
tag @e remove minecraft_but.deadly_colors.yellow.kill
tag @e remove minecraft_but.deadly_colors.green.kill
tag @e remove minecraft_but.deadly_colors.blue.kill
tag @e remove minecraft_but.deadly_colors.violet.kill
tag @e remove minecraft_but.deadly_colors.brown.kill
tag @e remove minecraft_but.deadly_colors.light.kill
tag @e remove minecraft_but.deadly_colors.dark.kill
tag @e remove minecraft_but.deadly_colors.red.kill
tag @e remove minecraft_but.deadly_colors.orange.kill
tag @e remove minecraft_but.deadly_colors.yellow.kill
tag @e remove minecraft_but.deadly_colors.green.kill
tag @e remove minecraft_but.deadly_colors.blue.kill
tag @e remove minecraft_but.deadly_colors.violet.kill
tag @e remove minecraft_but.deadly_colors.brown.kill
tag @e remove minecraft_but.deadly_colors.light.kill
tag @e remove minecraft_but.deadly_colors.dark.kill
tag @e remove minecraft_but.deadly_colors.red.kill
tag @e remove minecraft_but.deadly_colors.orange.kill
tag @e remove minecraft_but.deadly_colors.yellow.kill
tag @e remove minecraft_but.deadly_colors.green.kill
tag @e remove minecraft_but.deadly_colors.blue.kill
tag @e remove minecraft_but.deadly_colors.violet.kill
tag @e remove minecraft_but.deadly_colors.brown.kill
tag @e remove minecraft_but.deadly_colors.light.kill
tag @e remove minecraft_but.deadly_colors.dark.kill
tag @e remove minecraft_but.deadly_colors.red.kill
tag @e remove minecraft_but.deadly_colors.orange.kill
tag @e remove minecraft_but.deadly_colors.yellow.kill
tag @e remove minecraft_but.deadly_colors.green.kill
tag @e remove minecraft_but.deadly_colors.blue.kill
tag @e remove minecraft_but.deadly_colors.violet.kill
tag @e remove minecraft_but.deadly_colors.brown.kill
tag @e remove minecraft_but.deadly_colors.light.kill
tag @e remove minecraft_but.deadly_colors.dark.kill
tag @e remove minecraft_but.deadly_colors.red.kill
tag @e remove minecraft_but.deadly_colors.orange.kill
tag @e remove minecraft_but.deadly_colors.yellow.kill
tag @e remove minecraft_but.deadly_colors.green.kill
tag @e remove minecraft_but.deadly_colors.blue.kill
tag @e remove minecraft_but.deadly_colors.violet.kill
tag @e remove minecraft_but.deadly_colors.brown.kill
tag @e remove minecraft_but.deadly_colors.light.kill
tag @e remove minecraft_but.deadly_colors.dark.kill
tag @e remove minecraft_but.deadly_colors.red.kill
tag @e remove minecraft_but.deadly_colors.orange.kill
tag @e remove minecraft_but.deadly_colors.yellow.kill
tag @e remove minecraft_but.deadly_colors.green.kill
tag @e remove minecraft_but.deadly_colors.blue.kill
tag @e remove minecraft_but.deadly_colors.violet.kill
tag @e remove minecraft_but.deadly_colors.brown.kill
tag @e remove minecraft_but.deadly_colors.light.kill
tag @e remove minecraft_but.deadly_colors.dark.kill
tag @e remove minecraft_but.death_orb.this
tag @e remove minecraft_but.death_orb.this
tag @e remove minecraft_but.death_orb.spawn
tag @e remove minecraft_but.death_orb.init
tag @e remove minecraft_but.death_swap.self
tag @e remove minecraft_but.death_swap.swapped
tag @e remove minecraft_but.effect_arrows
tag @e remove minecraft_but.eeMarked
tag @e remove minecraft_but.eeMExists
tag @e remove minecraft_but.explosive_sight.ray
tag @e remove minecraft_but.esMarked
tag @e remove minecraft_but.esMExists
tag @e remove minecraft_but.fast_arrows
tag @e remove minecraft_but.herbivore.death_message
tag @e remove minecraft_but.mermaid.in_water
tag @e remove minecraft_but.mermaid.in_water
tag @e remove minecraft_but.mermaid.mercied
tag @e remove minecraft_but.mermaid.in_water
tag @e remove minecraft_but.mermaid.rain
tag @e remove minecraft_but.mermaid.in_water
tag @e remove minecraft_but.pacifist.death_message
tag @e remove minecraft_but.random_teleport.nether
tag @e remove minecraft_but.teleport_chorus.nether
tag @e remove minecraft_but.tnt_bats.detonated
tag @e remove minecraft_but.tnt_bats.spawned
tag @e remove minecraft_but.tnt_bats.spawned
tag @e remove minecraft_but.tnt_rain.destroy
tag @e remove minecraft_but.toxic_water.out_of_water
tag @e remove minecraft_but.toxic_water.out_of_water
tag @e remove minecraft_but.toxic_water.rain
tag @e remove minecraft_but.tparrow
tag @e remove minecraft_but.troglodyte.mercied
tag @e remove minecraft_but.vsNew
tag @e remove minecraft_but.vsMarked
tag @e remove minecraft_but.vsNoSlime
tag @e remove minecraft_but.hasID
tag @e remove todd


