name: Convert README
on:
  workflow_dispatch:
  push:
    paths:
      - 'README.md'
jobs: 
  setup-nodejs-env:
    uses: ./.github/workflows/reinstall-nodejs.yml
  update-version:
    name: Convert README
    runs-on: ubuntu-latest
    needs: 
      - setup-nodejs-env
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: "scripts/node_modules"
          key: node-modules-${{ hashFiles('scripts/package.json') }}
      - name: Update modifiers
        working-directory: ${{ github.workspace }}/scripts
        run: node convert-readme.cjs