name: Run update scripts
on:
  workflow_dispatch:
  push:
    paths:
      - './scripts/update/**.js'
      - './scripts/update/**.cjs'
      - './scripts/update/**.mjs'
jobs: 
  setup-nodejs-env:
    uses: ./.github/workflows/setup-nodejs.yml
  update-version:
    name: Update Minecraft version
    runs-on: ubuntu-latest
    needs: 
      - setup-nodejs-env
    steps:
      - uses: actions/checkout@v3
      - name: Update Minecraft version
        working-directory: ${{ github.workspace }}/scripts
        run: node update-version.js