name: Release cleanup
on:
  release:
    types:
      - published
  push:
    branches:
      - release/*
jobs:
  change-namespace:
    name: Change namespace
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      #- name: Git fetch
      #  run: git fetch --all
      - run: pwd
      - run: ls -la
      - name: Delete ignored files
        run: |
          git branch
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --cached .
      - name: Set .gitignore to release .gitignore
        run: mv ./.gitignores/release .gitignore
      - name: Debug - ls
        run: ls -lah ./data
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Action: Clean for release"
