name: Release cleanup
on:
  release:
    types:
      - published
  push:
    branches:
      - release/*
jobs:
  change-namespace:
    name: Change namespace
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      #- name: Git fetch
      #  run: git fetch --all
      - run: pwd
      - run: ls -la
      
      - name: Search & replace - *.mcfunction - s/abchc/minecraft_but.core/g
        run: find . -type f -name "*.mcfunction" -not -path ".git"  -print0 | xargs -0 sed -i'' -e 's/abchc/minecraft_but.core/g'
      - name: Search & replace - *.mcfunction - s/abch/minecraft_but/g
        run: find . -type f -name "*.mcfunction" -not -path ".git"  -print0 | xargs -0 sed -i'' -e 's/abch/minecraft_but/g'
      - name: Search & replace - *js - s/abchc/minecraft_but.core/g
        run: find . -type f -name "*.js" -not -path ".git"  -print0 | xargs -0 sed -i'' -e 's/abchc/minecraft_but.core/g'
      - name: Search & replace - *js - s/abch/minecraft_but/g
        run: find . -type f -name "*.js" -not -path ".git"  -print0 | xargs -0 sed -i'' -e 's/abch/minecraft_but/g'
      - name: Debug - ls
        run: ls -lah ./data
      - name: Rename abchc to minecraft_but.core
        run: mv ./data/abchc ./data/minecraft_but.core
      - name: Set .giignore to release .gitignore
        run: mv ./.gitignores/release .gitignore
      - name: Delete ignored files
        run: |
          git branch
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git rm -r --cached .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Action: Clean for release"
