name: Setup NodeJS environment
on:
  - workflow_dispatch
  - workflow_call
jobs: 
  setup-nodejs-env:
    name: Setup NodeJS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 19.x
      - uses: actions/cache@v3
        with:
          path: "scripts/node_modules"
          key: node-modules-${{ hashFiles('scripts/package.json') }}
