name: Update version
on:
  - workflow_dispatch
jobs: 
  setup-nodejs-env:
    uses: ./.github/workflows/setup-nodejs.yml
  update-version:
    name: Update Minecraft version
    runs-on: ubuntu-latest
    needs: 
      - setup-nodejs-env
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: "scripts/node_modules"
          key: node-modules-${{ hashFiles('scripts/package.json') }}
      - name: Update Minecraft version
        working-directory: ${{ github.workspace }}/scripts
        run: node update-version.js