name: Update modifiers
on:
  workflow_dispatch:
  push:
    paths:
      - './scripts/update-modifiers.cjs'
      - './scripts/modifiers.jsonc'
jobs: 
  setup-nodejs-env:
    uses: ./.github/workflows/reinstall-nodejs.yml
  update-version:
    name: Update modifiers
    runs-on: ubuntu-latest
    needs: 
      - setup-nodejs-env
    steps:
      - uses: actions/checkout@v3
      - name: Update modifiers
        working-directory: ${{ github.workspace }}/scripts
        run: node update-modifiers.cjs
