name: Update uninstall function
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs: 
  setup-nodejs-env:
    uses: ./.github/workflows/reinstall-nodejs.yml
  update-version:
    name: Update uninstall function
    runs-on: ubuntu-latest
    needs: 
      - setup-nodejs-env
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache/restore@v3
        with:
          path: "scripts/node_modules"
          key: node-modules-${{ hashFiles('scripts/package.json') }}
      - name: Install mcf-uninstall script
        run: npm i mcf-uninstall
      - name: Run mcf-uninstall
        working-directory: ${{ github.workspace }}/scripts
        run: npx mcf-uninstall ../data/minecraft_but.core/functions/ -v --tag "!global" --storage "!random" "!iris"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "GitHub Action: Update uninstall function"
