#> abchc:modifiers/random_structures/place_structure
#Function automatically generated by NodeJS script (src/index.js) to place a random structure
# 31 total structures 
# @within abchc:modifiers/random_structures/**
# @context marker

#> Get random number
scoreboard players set in abch.rng.math 1
scoreboard players set in1 abch.rng.math 31
function abchc:aps/rng/range

#> Place random structure
execute if score out abch.rng.math matches 0 run place structure minecraft:ancient_city ~ ~ ~
execute if score out abch.rng.math matches 1 run place structure minecraft:buried_treasure ~ ~ ~
execute if score out abch.rng.math matches 2 run place structure minecraft:desert_pyramid ~ ~ ~
execute if score out abch.rng.math matches 3 run place structure minecraft:end_city ~ ~ ~
execute if score out abch.rng.math matches 4 run place structure minecraft:igloo ~ ~ ~
execute if score out abch.rng.math matches 5 run place structure minecraft:jungle_pyramid ~ ~ ~
execute if score out abch.rng.math matches 6 run place structure minecraft:mineshaft ~ ~ ~
execute if score out abch.rng.math matches 7 run place structure minecraft:mineshaft_mesa ~ ~ ~
execute if score out abch.rng.math matches 8 run place structure minecraft:fortress ~ ~ ~
execute if score out abch.rng.math matches 9 run place structure minecraft:bastion_remnant ~ ~ ~
execute if score out abch.rng.math matches 10 run place structure minecraft:nether_fossil ~ ~ ~
execute if score out abch.rng.math matches 11 run place structure minecraft:monument ~ ~ ~
execute if score out abch.rng.math matches 12 run place structure minecraft:ocean_ruin_cold ~ ~ ~
execute if score out abch.rng.math matches 13 run place structure minecraft:ocean_ruin_warm ~ ~ ~
execute if score out abch.rng.math matches 14 run place structure minecraft:pillager_outpost ~ ~ ~
execute if score out abch.rng.math matches 15 run place structure minecraft:ruined_portal ~ ~ ~
execute if score out abch.rng.math matches 16 run place structure minecraft:ruined_portal_desert ~ ~ ~
execute if score out abch.rng.math matches 17 run place structure minecraft:ruined_portal_jungle ~ ~ ~
execute if score out abch.rng.math matches 18 run place structure minecraft:ruined_portal_swamp ~ ~ ~
execute if score out abch.rng.math matches 19 run place structure minecraft:ruined_portal_mountain ~ ~ ~
execute if score out abch.rng.math matches 20 run place structure minecraft:ruined_portal_ocean ~ ~ ~
execute if score out abch.rng.math matches 21 run place structure minecraft:ruined_portal_nether ~ ~ ~
execute if score out abch.rng.math matches 22 run place structure minecraft:shipwreck ~ ~ ~
execute if score out abch.rng.math matches 23 run place structure minecraft:shipwreck_beached ~ ~ ~
execute if score out abch.rng.math matches 24 run place structure minecraft:stronghold ~ ~ ~
execute if score out abch.rng.math matches 25 run place structure minecraft:swamp_hut ~ ~ ~
execute if score out abch.rng.math matches 26 run place structure minecraft:village_plains ~ ~ ~
execute if score out abch.rng.math matches 27 run place structure minecraft:village_desert ~ ~ ~
execute if score out abch.rng.math matches 28 run place structure minecraft:village_savanna ~ ~ ~
execute if score out abch.rng.math matches 29 run place structure minecraft:village_snowy ~ ~ ~
execute if score out abch.rng.math matches 30 run place structure minecraft:village_taiga ~ ~ ~
execute if score out abch.rng.math matches 31 run place structure minecraft:mansion ~ ~ ~

#> Visuals
function abchc:modifiers/random_structures/visuals

#> Kill marker
kill @s